
import { Link } from 'react-router-dom';
import Footer from '../components/Footer';
export default function AboutPage() {
  return <>
    <main id="main-content" tabIndex={-1} className="case-main">
      <header className="case-hero"><p className="section-label">Digital Product / CineVault</p><h1>A film for tonight.<br /><em>A collection for later.</em></h1><p className="case-lead">A movie-discovery application that turns browsing into a personal watchlist. Designed around a simple journey: find a title, understand it, and save it without creating an account.</p><Link to="/" className="btn-hero-primary">Explore the product ↗</Link><dl className="project-facts"><div><dt>Origin</dt><dd>Course final, independently refined</dd></div><div><dt>Focus</dt><dd>Interface design & frontend development</dd></div><div><dt>Stack</dt><dd>React · Vite · server-side API</dd></div><div><dt>Data</dt><dd>OMDb film information & posters</dd></div></dl></header>
      <section className="case-section case-overview" id="story" aria-labelledby="brief-title"><div><p className="section-label">01 / The brief</p><h2 id="brief-title">Less deciding.<br />More discovering.</h2></div><div><p>Film browsing can become a loop of opening tabs, forgetting titles, and starting again. CineVault’s design premise is to keep discovery and saving in the same place.</p><p>The project began as a Frontend Simplified React final project. This portfolio edition refines the interface, mobile navigation, accessibility, data handling, and project documentation. It is an independent demonstration, with no commissioned client or claimed commercial results.</p></div></section>
      <section className="case-section" id="how" aria-labelledby="journey-title"><p className="section-label">02 / The product journey</p><h2 id="journey-title">Three steps. One place.</h2><ol className="journey"><li><span>01</span><h3>Discover</h3><p>Start with a considered collection or search for a movie title. Clear labels distinguish curated selections from catalogue results.</p></li><li><span>02</span><h3>Understand</h3><p>Open film details for its synopsis, cast, director, runtime, and published ratings. Find a trailer through a clearly labelled YouTube search.</p></li><li><span>03</span><h3>Keep</h3><p>Save a title from its card, featured selection, or details. Revisit the watchlist after a reload, with no registration step.</p></li></ol></section>
      <section className="case-section" id="decisions" aria-labelledby="design-title"><p className="section-label">03 / Design decisions</p><h2 id="design-title">Cinema sets the tone.<br />Usability sets the pace.</h2><div className="decision-list"><article><span>01</span><div><h3>An editorial visual language</h3><p>Playfair Display gives film titles the presence of a cinema programme. Barlow keeps summaries readable, while condensed labels and restrained gold accents establish clear control hierarchy.</p></div></article><article><span>02</span><div><h3>Discovery without moving targets</h3><p>The featured selection starts still. Slideshow playback is optional, pauses during interaction, and respects reduced-motion preferences. Sorting changes the collection without rearranging its featured films.</p></div></article><article><span>03</span><div><h3>The same actions on every screen</h3><p>Mobile navigation retains collection access. Film details keep saving near the title. Native dialogs contain keyboard focus and return it to the opening control when dismissed.</p></div></article></div></section>
      <section className="case-section case-overview" id="engineering" aria-labelledby="engineering-title"><div><p className="section-label">04 / Engineering</p><h2 id="engineering-title">Small components.<br />Clear responsibilities.</h2></div><div><p>React Context separates movie discovery, watchlist state, and theme preferences. A central data service normalises API responses so interface components can work with a consistent film model.</p><ul className="engineering-list"><li><strong>Server-side credentials.</strong> A same-origin endpoint validates requests, keeps the API key out of the client, and caches responses for five minutes.</li><li><strong>Predictable requests.</strong> New searches cancel previous client requests. Film details load with limited concurrency, and partial failures produce a visible retry option.</li><li><strong>Search beyond one page.</strong> Pagination exposes additional catalogue matches, while sorting applies to the page currently shown.</li><li><strong>Resilient local state.</strong> Watchlist and theme preferences use browser storage with a session fallback when storage is unavailable.</li></ul></div></section>
      <section className="case-section case-overview" id="scope" aria-labelledby="scope-title"><div><p className="section-label">05 / Honest scope</p><h2 id="scope-title">A focused product.<br />Room to grow.</h2></div><div><p>This is a portfolio application, not a streaming service. Curated collections are editorial choices rather than current rankings. Film details and poster availability depend on OMDb.</p><ul className="engineering-list"><li>Watchlists belong to this browser; they do not sync across devices.</li><li>Search uses title matching, not personalised recommendations.</li><li>Trailer links open search results, not a verified individual video.</li><li>No user research outcomes, conversion gains, or commercial metrics are claimed.</li></ul><p>Useful next steps would be testing title discovery and saving with real users, then deciding whether filters or cross-device watchlists solve the problems observed.</p><a href="https://www.omdbapi.com/" className="case-source" target="_blank" rel="noopener noreferrer">About the data source ↗</a></div></section>
      <section className="case-cta"><p className="section-label">The next scene is yours</p><h2>Find something<br /><em>worth watching.</em></h2><Link to="/" className="btn-hero-primary">Discover films ↗</Link></section>
    </main>
    <Footer />
  </>;
}
